### ISSUE TITLE
Still Works

### ISSUE THREAD

**Issue by lucenajj** [jrCleber/n8n-codechat-wapi#2]
I'm trying to use this node but without success, does it still work?
Version N8N 1.63.4

**Comment by jrCleber** [comment]
Good morning! We need to adjust the compatibility.
This project was archived. I unarchived it to update it in the next few weeks.

**Comment by lucenajj** [comment]
Obrigado pelo retorno

Em qua., 23 de out. de 2024, 09:42, Cleber Wilson ***@***.***>
escreveu:
